### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by vladventura** [patchoulisystems/digitalsign#15]
If for some reason there's no scheduled pictures for that day, we can serve a single picture that serves as placeholder, saying there's no pictures to show. Definitively should do the same for when something happens when serving an image, or when showing it as well. TL;DR: 

- When a 500 triggers, send ISE picture
- When picture is not found, send Picture not Found picture

**Comment by patchoulisystems** [comment]
can we flag the calendar dates that don't have an image/slideshow with an alert icon?

**Comment by vladventura** [comment]
This issue is fixed and the comment is also addressed in a branch as well
