### ISSUE TITLE
Set up a logger by service start date

### ISSUE THREAD

**Issue by vladventura** [patchoulisystems/digitalsign#6]
Fairly simple but this will need it's own branch naturally. We can set up Winston and Moment maybe, but if we do end up getting Moment then might as well replace Date with Moment. This will help us know if something goes wrong with the app at any given time and it will also help us/me (because I'll most likely be the one still in campus this upcoming fall right? lol) with debugging if someone calls us because something went wrong with it.

**Comment by patchoulisystems** [comment]
iirc systemd has a solution for organizing and saving logs, I can look into that, but access to the logs will be limited by the pi's access to internet probably

**Comment by vladventura** [comment]
Sounds good. As long as there's at least something to look at if it breaks. Closing
