### ISSUE TITLE
Add Forever to the app

### ISSUE THREAD

**Issue by vladventura** [patchoulisystems/digitalsign#7]
See https://www.npmjs.com/package/forever for more info, but the TL;DR is that this will increment the app's self sustainability. We can wrap the node app.js with it and then, if by any chance the app dies we can be confident that it'll come back up, like a zombie.

**Comment by patchoulisystems** [comment]
systemd should be handling this already, it will restart the service if it fails

**Comment by vladventura** [comment]
Ahh perfect, sounds good; closing
